runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  # You can also specify 2 for Python 2.7
  python_version: 2.7

handlers:
- url: /.*
  script: Galerts.app

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "latest"
-name: galerts
 version: "0.1.5"