application: Galerts.py
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: Galerts.py

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "latest"
-name: galerts
 version: "0.1.5"